Repository TeamHARA/HARA_iOS, pull requests merged in 2023-01, with the labels that each got.

#5 [Feat] tabbar 수정 및 write view 세팅
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HARA/HARA/Global/Extension/UIColor+.swift
  HARA/HARA/Resources/Assets.xcassets/Together/icn_close.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/icn_close.imageset/icn_close.png
  HARA/HARA/Resources/Assets.xcassets/Together/icn_close.imageset/icn_close@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/icn_close.imageset/icn_close@3x.png
  HARA/HARA/Resources/Assets.xcassets/background.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/background.imageset/Rectangle 4263.png
  HARA/HARA/Resources/Assets.xcassets/background.imageset/Rectangle 4263@2x.png
  HARA/HARA/Resources/Assets.xcassets/background.imageset/Rectangle 4263@3x.png
  HARA/HARA/Sources/HaraTabBarController.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FifthStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FirstStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FourthStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/SecondStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/ThirdStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: 🖼 UI, 🏗 Feat

#7 [Feat] Together-Header&Category UI 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Global/Extension/UICollectionVIew+.swift
  HARA/HARA/Resources/Assets.xcassets/Navigation/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Navigation/logo_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Navigation/logo_icon.imageset/logo.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/logo_icon.imageset/logo@2x.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/logo_icon.imageset/logo@3x.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/search_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Navigation/search_icon.imageset/icnSearch.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/search_icon.imageset/icnSearch@2x.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/search_icon.imageset/icnSearch@3x.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/setting_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Navigation/setting_icon.imageset/icnSetting.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/setting_icon.imageset/icnSetting@2x.png
  HARA/HARA/Resources/Assets.xcassets/Navigation/setting_icon.imageset/icnSetting@3x.png
  HARA/HARA/Sources/Components/DefaultNavigationView.swift
  HARA/HARA/Sources/Scenes/Together/CategoryCVC.swift
  HARA/HARA/Sources/Scenes/Together/TogetherVC.swift
Labels: 🖼 UI

#10 [Feat] 함께해라 고민글 카드뷰 UI 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/Together/together_chat_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/together_chat_icon.imageset/icn_chat.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_chat_icon.imageset/icn_chat@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_chat_icon.imageset/icn_chat@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_checked_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/together_checked_icon.imageset/icn_checkcircle_on.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_checked_icon.imageset/icn_checkcircle_on@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_checked_icon.imageset/icn_checkcircle_on@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_unChecked_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/together_unChecked_icon.imageset/icn_checkcircle_off.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_unChecked_icon.imageset/icn_checkcircle_off@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_unChecked_icon.imageset/icn_checkcircle_off@3x.png
  HARA/HARA/Sources/Components/DefaultNavigationView.swift
  HARA/HARA/Sources/Scenes/Together/TogetherVC.swift
  HARA/HARA/Sources/Scenes/Together/VoteOptionCVC.swift
  HARA/HARA/Sources/Scenes/Together/WorryCardCVC.swift
Labels: 🖼 UI

#13 Feat/#4 worried alone page UI
  .idea/.gitignore
  .idea/HARA_iOS.iml
  .idea/modules.xml
  .idea/vcs.xml
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Global/Extension/Adjusted+.swift
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_Bell.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_Bell.imageset/icn_Bell.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_Bell.imageset/icn_Bell@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_Bell.imageset/icn_Bell@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_logo.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_logo.imageset/logo.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_logo.imageset/logo@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_logo.imageset/logo@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_setting_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_setting_icon.imageset/icn_setting.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_setting_icon.imageset/icn_setting@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_setting_icon.imageset/icn_setting@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/strorage_oneclick_btn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/strorage_oneclick_btn.imageset/btn_sec.png
  HARA/HARA/Resources/Assets.xcassets/Storage/strorage_oneclick_btn.imageset/btn_sec@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/strorage_oneclick_btn.imageset/btn_sec@3x.png
  HARA/HARA/Resources/FirstViewController.swift
  HARA/HARA/Resources/prac.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
  HARA/HARA/Sources/Scenes/Storage/UnderlineSegmentedControl.swift
Labels: 🖼 UI

#15 [Feat] 고민 선택지 개수별 고민 카드 셀 높이 조정
  HARA/HARA/Sources/Scenes/Together/TogetherVC.swift
  HARA/HARA/Sources/Scenes/Together/WorryCardCVC.swift
Labels: 🏗 Feat

#18 [Feat] write vc UI(1, 4, 5번째 페이지)
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/WriteVC/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/icn_close.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/icn_close.imageset/icn_close.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/icn_close.imageset/icn_close@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/icn_close.imageset/icn_close@3x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/nextBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/nextBtn.imageset/Vector 2644-1.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/nextBtn.imageset/Vector 2644@2x-1.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/nextBtn.imageset/Vector 2644@3x-1.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/prevBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/prevBtn.imageset/Vector 2644.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/prevBtn.imageset/Vector 2644@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/prevBtn.imageset/Vector 2644@3x.png
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FifthStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FifthWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FirstWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FourthStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FourthWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/SecondStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/SecondWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/ThirdStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/ThirdWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: 🖼 UI, 🏗 Feat

#20 [Feat] 1, 4, 5번째 writeStepView 수정 사항 반영 및 누락된 변경사항 추가
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Global/Extension/UIFont+.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FifthWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FirstWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FourthWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/OptionView/AddOptionView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/OptionView/BaseOptionView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/SecondWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/ThirdWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: 🐞Bug&Fix, 🖼 UI, 🏗 Feat

#17 [Feat] storage collection view cell UI 구현하기
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/icn_checkcircle_off.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/icn_checkcircle_off@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/icn_checkcircle_off@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/icn_checkcircle_on.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/icn_checkcircle_on@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/icn_checkcircle_on@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/tag_complete.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/tag_complete@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/tag_complete@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/icn_complete.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/icn_complete@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/icn_complete@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/tag_ing.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/tag_ing@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/tag_ing@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/icn_ing.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/icn_ing@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/icn_ing@3x.png
  HARA/HARA/Sources/Scenes/Storage/AloneWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/AloneWorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/TogetherWorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
  HARA/HARA/Sources/Scenes/Storage/TogetherWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/TogetherWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/UnderlineSegmentedControl.swift
Labels: 🖼 UI

#27 [Feat] #26- StorageVC CollectionViewCell 생성
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/icn_checkcircle_off.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/icn_checkcircle_off@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_off.imageset/icn_checkcircle_off@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/icn_checkcircle_on.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/icn_checkcircle_on@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_check_on.imageset/icn_checkcircle_on@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/tag_complete.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/tag_complete@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete.imageset/tag_complete@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/icn_complete.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/icn_complete@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_complete_all.imageset/icn_complete@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/tag_ing.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/tag_ing@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing.imageset/tag_ing@3x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/icn_ing.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/icn_ing@2x.png
  HARA/HARA/Resources/Assets.xcassets/Storage/storage_ing_all.imageset/icn_ing@3x.png
  HARA/HARA/Sources/Scenes/Storage/AloneWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/AloneWorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/TogetherWorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
  HARA/HARA/Sources/Scenes/Storage/TogetherWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/TogetherWorriedVC.swift
Labels: 🐞Bug&Fix, 🖼 UI, 🏗 Feat

#22 [Feat] 함께 고민 카드내 투표 기능 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/Together/together_check_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/together_check_icon.imageset/icn_check.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_check_icon.imageset/icn_check@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_check_icon.imageset/icn_check@3x.png
  HARA/HARA/Sources/Scenes/Together/VoteOptionCVC.swift
  HARA/HARA/Sources/Scenes/Together/VotedCVC.swift
  HARA/HARA/Sources/Scenes/Together/WorryCardCVC.swift
Labels: 🏗 Feat

#24 [Feat] secondWriteStepView의 optionStackView 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/WriteVC/addOptionBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/addOptionBtn.imageset/icn_add.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/addOptionBtn.imageset/icn_add@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/addOptionBtn.imageset/icn_add@3x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/closeBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/closeBtn.imageset/icn_close.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/closeBtn.imageset/icn_close@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/closeBtn.imageset/icn_close@3x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/deleteOptionBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/deleteOptionBtn.imageset/icn_delete_list.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/deleteOptionBtn.imageset/icn_delete_list@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/deleteOptionBtn.imageset/icn_delete_list@3x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/insertImageBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/insertImageBtn.imageset/icn_image.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/insertImageBtn.imageset/icn_image@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/insertImageBtn.imageset/icn_image@3x.png
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FirstWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/FourthWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/OptionView/AddOptionBtnView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/OptionView/AddOptionView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/OptionView/BaseOptionView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/SecondWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/ThirdWriteStepView.swift
Labels: 🖼 UI, 🏗 Feat

#29 [Feat] thirdWriteStepView 컬렉션 뷰 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Global/Extension/NSObject+.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FifthWriteStepVC/FifthWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FirstWriteStepVC/FirstWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FourthWriteStepVC/FourthWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/SecondWriteStepVC/OptionView/AddOptionBtnView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/SecondWriteStepVC/OptionView/AddOptionView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/SecondWriteStepVC/OptionView/BaseOptionView.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/SecondWriteStepVC/SecondWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ProsConsCVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ThirdWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepView/ThirdWriteStepView.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: 🖼 UI, 🏗 Feat

#31 [Feat] 1초만에 고민 해결하기 뷰 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Global/Extension/UIFont+.swift
  HARA/HARA/Resources/Assets.xcassets/StorageVC/Contents.json
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerBackground.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerBackground.imageset/Frame 735.png
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerBackground.imageset/Frame 735@2x.png
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerBackground.imageset/Frame 735@3x.png
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerResultBackground.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerResultBackground.imageset/Frame 735.png
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerResultBackground.imageset/Frame 735@2x.png
  HARA/HARA/Resources/Assets.xcassets/StorageVC/answerResultBackground.imageset/Frame 735@3x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/Contents.json
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_chat_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_chat_icon.imageset/icn_chat.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_chat_icon.imageset/icn_chat@2x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_chat_icon.imageset/icn_chat@3x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_check_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_check_icon.imageset/icn_check.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_check_icon.imageset/icn_check@2x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_check_icon.imageset/icn_check@3x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_checked_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_checked_icon.imageset/icn_checkcircle_on.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_checked_icon.imageset/icn_checkcircle_on@2x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_checked_icon.imageset/icn_checkcircle_on@3x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_tab_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_tab_icon.imageset/icn_home.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_tab_icon.imageset/icn_home@2x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_tab_icon.imageset/icn_home@3x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_unChecked_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_unChecked_icon.imageset/icn_checkcircle_off.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_unChecked_icon.imageset/icn_checkcircle_off@2x.png
  HARA/HARA/Resources/Assets.xcassets/TogetherVC/together_unChecked_icon.imageset/icn_checkcircle_off@3x.png
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/UnderlineSegmentedControl.swift
  HARA/HARA/Sources/Scenes/Storage/OneSecondPage/OneSecGameVC.swift
  HARA/HARA/Sources/Scenes/Storage/OneSecondPage/RecentWorryCVC.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/RecentWorryModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ThirdWriteStepVC.swift
Labels: 🖼 UI, 🏗 Feat

#33 [Feat] 고민 상세보기 뷰 UI 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_checked_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_checked_icon.imageset/icnAnonymityOn.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_checked_icon.imageset/icnAnonymityOn@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_checked_icon.imageset/icnAnonymityOn@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_close_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_close_icon.imageset/icn_close.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_close_icon.imageset/icn_close@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_close_icon.imageset/icn_close@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_send_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_send_icon.imageset/icnSend.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_send_icon.imageset/icnSend@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_send_icon.imageset/icnSend@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_unChecked_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_unChecked_icon.imageset/icnAnonymityOff.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_unChecked_icon.imageset/icnAnonymityOff@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/detailWorry_unChecked_icon.imageset/icnAnonymityOff@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_profile_icon.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/together_profile_icon.imageset/icn_profile.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_profile_icon.imageset/icn_profile@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/together_profile_icon.imageset/icn_profile@3x.png
  HARA/HARA/Sources/Scenes/Together/CommentHeaderView.swift
  HARA/HARA/Sources/Scenes/Together/DetailWorryCVC.swift
  HARA/HARA/Sources/Scenes/Together/DetailWorryCardVC.swift
  HARA/HARA/Sources/Scenes/Together/DetailWorryCommentCVC.swift
  HARA/HARA/Sources/Scenes/Together/TogetherVC.swift
  HARA/HARA/Sources/Scenes/Together/VoteOptionCVC.swift
  HARA/HARA/Sources/Scenes/Together/WorryCardCVC.swift
  HARA/HARA/Sources/Scenes/Together/WorryDetailFooterView.swift
  HARA/HARA/Sources/Scenes/Together/WorryDetailHeaderView.swift
Labels: 🖼 UI, 🏗 Feat

#36 [Feat] pageVC buttonlogic 구현
  HARA/HARA/Resources/Assets.xcassets/WriteVC/categoryBtn.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/WriteVC/categoryBtn.imageset/icn_.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/categoryBtn.imageset/icn_@2x.png
  HARA/HARA/Resources/Assets.xcassets/WriteVC/categoryBtn.imageset/icn_@3x.png
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FirstWriteStepVC/FirstWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FourthWriteStepVC/FourthWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/SecondWriteStepVC/SecondWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ThirdWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: 🏗 Feat

#40 [Chore] StorageVC 글자 위치, 스크롤 해결
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/UnderlineSegmentedControl.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/AloneWorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/WorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
Labels: 🖼 UI

#44 [Feat] Base 네트워크 파일 세팅
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Network/Base/APIConstant.swift
  HARA/HARA/Network/Base/BaseTargetType.swift
  HARA/HARA/Network/Base/GeneralResponse.swift
  HARA/HARA/Network/Base/MoyLoggingPlugin.swift
  HARA/HARA/Network/Base/NetworkConstant.swift
  HARA/HARA/Network/Base/NetworkResult.swift
  HARA/HARA/Network/DataModel/Storage/StorageResponse.swift
  HARA/HARA/Network/DataModel/Together/TogetherResponse.swift
  HARA/HARA/Network/DataModel/Write/WriteResponse.swift
  HARA/HARA/Network/Services/TogetherService.swift
Labels: 📡 Network

#47 [Feat] 최종 결정하기 뷰 UI 및 로직 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Resources/Assets.xcassets/Together/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/dummy1_img.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/dummy1_img.imageset/Rectangle 828412.png
  HARA/HARA/Resources/Assets.xcassets/Together/dummy1_img.imageset/Rectangle 828412@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/dummy1_img.imageset/Rectangle 828412@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/finalBackground_img.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/finalBackground_img.imageset/background.png
  HARA/HARA/Resources/Assets.xcassets/Together/finalBackground_img.imageset/background@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/finalBackground_img.imageset/background@3x.png
  HARA/HARA/Resources/Assets.xcassets/Together/final_title_img.imageset/Contents.json
  HARA/HARA/Resources/Assets.xcassets/Together/final_title_img.imageset/decide_text_result.png
  HARA/HARA/Resources/Assets.xcassets/Together/final_title_img.imageset/decide_text_result@2x.png
  HARA/HARA/Resources/Assets.xcassets/Together/final_title_img.imageset/decide_text_result@3x.png
  HARA/HARA/Sources/Scenes/Together/FinalChoice/FinalChoiceCVC.swift
  HARA/HARA/Sources/Scenes/Together/FinalChoice/FinalChoiceVC.swift
  HARA/HARA/Sources/Scenes/Together/FinalChoice/FinalWorryDoneVC.swift
Labels: 🖼 UI, 🏗 Feat

#51 [Feat] writeVC 서버 연결 post 구현
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Network/APIs/WriteAPI.swift
  HARA/HARA/Network/Base/APIConstant.swift
  HARA/HARA/Network/DataModel/Write/WriteRequest.swift
  HARA/HARA/Network/Services/WriteService.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FifthWriteStepVC/FifthWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FirstWriteStepVC/FirstWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FourthWriteStepVC/FourthWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ProsConsCVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ThirdWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: 📡 Network

#48 [Feat] StorageVC network 구현 성공
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Network/APIs/StorageAPI.swift
  HARA/HARA/Network/Base/APIConstant.swift
  HARA/HARA/Network/DataModel/Storage/StorageAloneResponse.swift
  HARA/HARA/Network/DataModel/Storage/StorageResponse.swift
  HARA/HARA/Network/Services/StorageService.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/UnderlineSegmentedControl.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/WorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
Labels: 📡 Network

#55 [Chore] Layout 수정 및 컨벤션에 맞게 코드 수정
  HARA/HARA.xcodeproj/project.pbxproj
  HARA/HARA/Application/AppDelegate.swift
  HARA/HARA/Application/SceneDelegate.swift
  HARA/HARA/Network/APIs/WriteAPI.swift
  HARA/HARA/Network/DataModel/Write/WriteResponse.swift
  HARA/HARA/Network/Services/StorageService.swift
  HARA/HARA/Sources/Components/SomeTemplate.swift
  HARA/HARA/Sources/Components/StorageNavigationView.swift
  HARA/HARA/Sources/Components/TogetherNavigationView.swift
  HARA/HARA/Sources/HaraTabBarController.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/AloneWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedCVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/TogetherWorriedVC.swift
  HARA/HARA/Sources/Scenes/Storage/AloneTogetherTab/UnderlineSegmentedControl.swift
  HARA/HARA/Sources/Scenes/Storage/OneSecondPage/OneSecGameVC.swift
  HARA/HARA/Sources/Scenes/Storage/StorageModel/WorriedModel.swift
  HARA/HARA/Sources/Scenes/Storage/StorageVC.swift
  HARA/HARA/Sources/Scenes/Together/CategoryCVC.swift
  HARA/HARA/Sources/Scenes/Together/TogetherVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/FourthWriteStepVC/FourthWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/SecondWriteStepVC/SecondWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteStepVC/ThirdWriteStepVC/ThirdWriteStepVC.swift
  HARA/HARA/Sources/Scenes/Write/WriteVC.swift
Labels: ✅ Chore, 🖼 UI
